# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'type2DProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift'

  # Pods for type2DProj

end
